### ISSUE TITLE
about pretrained model

### ISSUE THREAD

**Issue by Q-Zhang98** [JunlinHan/CWR#9]
The image I generated using the pre-trained model has black dots in the upper left corner
![1](https://user-images.githubusercontent.com/94459772/195544657-cb49e90b-b43f-42bf-80ce-ab9d0bef9a8b.png)

**Comment by JunlinHan** [comment]
Hello,
Yes, the result can be bad when performing underwater image enhancement tasks.
Please try this CWR pre-trained on HICRD, fine-tuned on UIEB: https://drive.google.com/file/d/1MCYZcAjKAf3y_rSNes_Fs3tm7L0U_77e/view?usp=sharing

**Comment by Q-Zhang98** [comment]
> 

OK, Thank u!

**Comment by Q-Zhang98** [comment]
> Hello, Yes, the result can be bad when performing underwater image enhancement tasks. Please try this CWR pre-trained on HICRD, fine-tuned on UIEB: https://drive.google.com/file/d/1MCYZcAjKAf3y_rSNes_Fs3tm7L0U_77e/view?usp=sharing

Sorry, did you use all 890 UIEB images and fine-tune them? How do you do that? I want to fine-tune on 800 and test with 90. Thank you very much

**Comment by JunlinHan** [comment]
> > Hello, Yes, the result can be bad when performing underwater image enhancement tasks. Please try this CWR pre-trained on HICRD, fine-tuned on UIEB: https://drive.google.com/file/d/1MCYZcAjKAf3y_rSNes_Fs3tm7L0U_77e/view?usp=sharing
> 
> Sorry, did you use all 890 UIEB images and fine-tune them? How do you do that? I want to fine-tune on 800 and test with 90. Thank you very much

I use the first 90 images as train data and other 800 images as test data. So there might be some overlaps with your data split. You may fine-tune the pretrained CWR model for 5-10 epochs following your data split.

**Comment by Q-Zhang98** [comment]
> > > Hello, Yes, the result can be bad when performing underwater image enhancement tasks. Please try this CWR pre-trained on HICRD, fine-tuned on UIEB: https://drive.google.com/file/d/1MCYZcAjKAf3y_rSNes_Fs3tm7L0U_77e/view?usp=sharing
> > 
> > 
> > Sorry, did you use all 890 UIEB images and fine-tune them? How do you do that? I want to fine-tune on 800 and test with 90. Thank you very much
> 
> I use the first 90 images as train data and other 800 images as test data. So there might be some overlaps with your data split. You may fine-tune the pretrained CWR model for 5-10 epochs following your data split.

I used the fine-tuned model you provided and still had the clolor blocks. How to remove it?
![918_img_](https://user-images.githubusercontent.com/94459772/195753016-dbbf11e9-8286-4235-9d92-5ebb2e117ab2.png)

**Comment by JunlinHan** [comment]
> > > > Hello, Yes, the result can be bad when performing underwater image enhancement tasks. Please try this CWR pre-trained on HICRD, fine-tuned on UIEB: https://drive.google.com/file/d/1MCYZcAjKAf3y_rSNes_Fs3tm7L0U_77e/view?usp=sharing
> > > 
> > > 
> > > Sorry, did you use all 890 UIEB images and fine-tune them? How do you do that? I want to fine-tune on 800 and test with 90. Thank you very much
> > 
> > 
> > I use the first 90 images as train data and other 800 images as test data. So there might be some overlaps with your data split. You may fine-tune the pretrained CWR model for 5-10 epochs following your data split.
> 
> I used the fine-tuned model you provided and still had the clolor blocks. How to remove it? ![918_img_](https://user-images.githubusercontent.com/94459772/195753016-dbbf11e9-8286-4235-9d92-5ebb2e117ab2.png)

Train/fine-tune it for longer epochs  should solve it.

**Comment by Q-Zhang98** [comment]
> > > > > Hello, Yes, the result can be bad when performing underwater image enhancement tasks. Please try this CWR pre-trained on HICRD, fine-tuned on UIEB: https://drive.google.com/file/d/1MCYZcAjKAf3y_rSNes_Fs3tm7L0U_77e/view?usp=sharing
> > > > 
> > > > 
> > > > Sorry, did you use all 890 UIEB images and fine-tune them? How do you do that? I want to fine-tune on 800 and test with 90. Thank you very much
> > > 
> > > 
> > > I use the first 90 images as train data and other 800 images as test data. So there might be some overlaps with your data split. You may fine-tune the pretrained CWR model for 5-10 epochs following your data split.
> > 
> > 
> > I used the fine-tuned model you provided and still had the clolor blocks. How to remove it? ![918_img_](https://user-images.githubusercontent.com/94459772/195753016-dbbf11e9-8286-4235-9d92-5ebb2e117ab2.png)
> 
> Train/fine-tune it for longer epochs should solve it.

I fine-tuned 50 epochs on UIEB and it's still the same.Using pre-trained models will also have this problem on HICRD.Could it be a problem with the pre-trained model? Is there a better pre-trained model？

**Comment by JunlinHan** [comment]
> > > > > > Hello, Yes, the result can be bad when performing underwater image enhancement tasks. Please try this CWR pre-trained on HICRD, fine-tuned on UIEB: https://drive.google.com/file/d/1MCYZcAjKAf3y_rSNes_Fs3tm7L0U_77e/view?usp=sharing
> > > > > 
> > > > > 
> > > > > Sorry, did you use all 890 UIEB images and fine-tune them? How do you do that? I want to fine-tune on 800 and test with 90. Thank you very much
> > > > 
> > > > 
> > > > I use the first 90 images as train data and other 800 images as test data. So there might be some overlaps with your data split. You may fine-tune the pretrained CWR model for 5-10 epochs following your data split.
> > > 
> > > 
> > > I used the fine-tuned model you provided and still had the clolor blocks. How to remove it? ![918_img_](https://user-images.githubusercontent.com/94459772/195753016-dbbf11e9-8286-4235-9d92-5ebb2e117ab2.png)
> > 
> > 
> > Train/fine-tune it for longer epochs should solve it.
> 
> I fine-tuned 50 epochs on UIEB and it's still the same.Using pre-trained models will also have this problem on HICRD.Could it be a problem with the pre-trained model? Is there a better pre-trained model？

If so, this issue can be hard to solve... Usually such checkboard effects are gone after longer training epochs. Could you please try train it from scratch, that is, no pre-trained models?
